### ISSUE TITLE
Using "Interface" suffix

### ISSUE THREAD

**Issue by RadnoK** [BitBagCommerce/BitBagBible#3]
There was a discussion about having `Interface` suffix interface classes. There are some pros and cons. Let's discuss this in this Issue.

Related comment: https://github.com/BitBagCommerce/BitBagBible/pull/1#discussion_r254172572

**Comment by damonsson** [comment]
I am against the removing that suffix. 

Pros:
- Forces us to deliberately use interfaces and finally better code

Cons from my perspective:
- Searching by filenames can be harder without Interface suffix when we need to find a related interface
- Looking on files for example on GitHub website can be harder because, for example, we want to look just on code into a class, and we can omit interfaces files because we know these are interfaces because of Interface suffix.
- From Symfony Coding Standards: `Suffix interfaces with Interface;`
